config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'welcome#index'

resources :users

resources :locations do
  resources :cohorts do
    resources :students do
    end
  end
end

resources :assignments do
  resources :submissions do
    member do
    post :create_comment
    delete :delete_comment
    end
    member do
    put :review
    put :done
    put :undone
    end
  end
end

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  belongs_to :location
  has_many :students

  validates :course, presence: :true
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  def index
    # @location - Location.find params[:location_id]
    authorize @cohort, :index?
  end

  def show
    @location = Location.find params[:location_id]
    @cohort = Cohort.find params[:id]
    
    authorize @cohort, :show?
  end

  def new
    @location = Location.find params[:location_id]
    @cohort = Cohort.new
    authorize @cohort, :new?
  end

  def edit
    @location = Location.find params[:location_id]
    authorize @cohort, :edit?
  end

  def create
    @location = Location.find params[:location_id]
    @cohort = @location.cohorts.new(cohort_params)
    authorize @cohort, :create?
    respond_to do |format|
        if @cohort.save
          format.html { redirect_to location_path(@location), notice: 'Cohort was successfully added!' }
        else
          format.html { render :new }
        end
      end
    end

  def update
    @location = Location.find params[:location_id]
    authorize @cohort, :update?
      if @cohort.update(cohort_params)
        redirect_to locations_path  
      else
        render :edit
      end
    end

  def destroy
    @location = Location.find params[:location_id]
    @cohort.destroy
    authorize @cohort, :destroy?
    respond_to do |format|
      format.html { redirect_to locations_path(@location), notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cohort
      @cohort = Cohort.find params[:id]
    end

    def cohort_params
      params.require(:cohort).permit(:course)
    end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.haml
.jumbotron
  = form_for [@location, @cohort] do |f|
    - if @cohort.errors.any?
      #error_explanation
        %h2= "#{pluralize(@cohort.errors.count, "error")} prohibited this cohort from being saved:"
        %ul
          - @cohort.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :course
      = f.text_field :course, class: "form-control", placeholder: "Please fill out the course name"
    .form-group    
      = f.submit 'Save'

app/views/cohorts/edit.html.haml
= render 'form'

app/views/cohorts/new.html.haml
%center
  %h1 New Cohort

  = render 'form'

app/views/cohorts/show.html.haml
.jumbotron
  %center
    %h1.cohort Class
    = @cohort.course
    %br
    %br
    = button_to "Add Student", new_location_cohort_student_path(@location, @cohort), method: :get, class: "buttonlink"
    %br
    %br
    %br
      - @cohort.students.each do |student|
        %li
          %strong
            = link_to "#{student.first_name} - #{student.last_name}", location_cohort_student_path(@location, @cohort, student)
            |
            = link_to "Edit", edit_location_cohort_student_path(@location, @cohort, student)
            |
            = link_to "Delete", location_cohort_student_path(@location, @cohort, student), method: :delete
    %br
    - if current_user.admin?
      = button_to "Assign homework", new_assignment_path(@assignment), class: "buttonlink", method: :get
    %br
    %br
    = button_to "Current Assignments", assignments_path, class: "buttonlink", method: :get