config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'welcome#index'

resources :users

resources :locations do
  resources :cohorts do
    resources :students do
    end
  end
end

resources :assignments do
  resources :submissions do
    member do
    post :create_comment
    delete :delete_comment
    end
    member do
    put :review
    put :done
    put :undone
    end
  end
end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :student
  has_many :comments, as: :commentable
  has_many :submissions

  validates :name, presence: :true
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @assignments = Assignment.all
    # authorize @assignment, :index?
  end

  def show
    @assignment = Assignment.find params[:id]
    authorize @assignment, :show?
  end

  def new
    @assignment = Assignment.new
    authorize @assignment, :new?
  end

  def create
    @assignment = Assignment.create assignment_params
    authorize @assignment, :create?
    redirect_to assignment_path(@assignment)
  end

  def edit
    @assignment = Assignment.find params[:id]
    authorize @assignment, :edit?
  end

  def update
    @assignment = Assignment.find params[:id]
    @assignment.update_attributes assignment_params
    authorize @assignment, :update?
    redirect_to assignments_path
  end

  def destroy
    @assignment = Assignment.find params[:id]
    @assignment.delete
    authorize @assignment, :destroy?
    redirect_to assignments_path
  end

  private
  def assignment_params
    params.require(:assignment).permit(:name, :description)
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.haml
.jumbotron
  = form_for @assignment do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control", placeholder: "Subject of your assignment"
    .form-group
      = f.label :description
      = f.text_area :description, :cols => "30", :rows => "10", class: "form-control", placeholder: "Write up a description of the assignment"
      %br
    %center
      = f.submit 'Submit'

app/views/assignments/edit.html.haml
= render 'form'

app/views/assignments/index.html.haml
.jumbotron 
  %center
    %h1.assignments Assignments
    %br
    = button_to "Add assignment", new_assignment_path, method: :get, class: "buttonlink"
    %br
      - @assignments.each do |assignment|
        %li
          %strong
            = link_to assignment.name, assignment_path(assignment)
            = assignment.description
            |
            = link_to "Edit", edit_assignment_path(assignment)
            |
            = link_to "Delete", assignment_path(assignment), method: :delete
    = button_to "Home", root_path, class: "buttonlink", method: :get

app/views/assignments/new.html.haml
= render 'form'

app/views/assignments/show.html.haml
.jumbotron
  %center
    %h1 Assignment
    %strong
      = @assignment.name
    %br
    %br
    %strong
      Description
      %br
    = @assignment.description
    %br
    %br
    = button_to "Submit Homework", new_assignment_submission_path(@assignment), class: "buttonlink", method: :get
    %br
    = button_to "Submissions", assignment_submissions_path(@assignment), class: "buttonlink", method: :get