config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'welcome#index'

resources :users

resources :locations do
  resources :cohorts do
    resources :students do
    end
  end
end

resources :assignments do
  resources :submissions do
    member do
    post :create_comment
    delete :delete_comment
    end
    member do
    put :review
    put :done
    put :undone
    end
  end
end

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :student
  
  has_many :comments, as: :commentable
  validates :name, presence: :true
  belongs_to :assignment

  include Workflow
  workflow do
    state :new do
      event :review, transitions_to: :reviewing
    end
    state :reviewing do
      event :done, transitions_to: :complete
      event :undone, transitions_to: :incomplete
    end
    state :incomplete do
      event :review, transitions_to: :reviewing
      event :done, transitions_to: :complete
    end
    state :complete
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def index
    @assignment = Assignment.find params[:assignment_id]
    @submissions = Submission.all
    # authorize @submission, :index?
  end

  def show
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @comment = @submission.comments.new
    authorize @submission, :show?
  end

  def new
    @submission = Submission.new
    @assignment = Assignment.find params[:assignment_id]
    # authorize @submission, :new?
  end

  def create
    @assignment = Assignment.find params[:assignment_id]
    @submission = @assignment.submissions.new(submission_params)
    # authorize @submission, :create?
    respond_to do |format|
    if @submission.save
      format.html { redirect_to assignment_submissions_path(@assignment), notice: 'Submission was successfully added!' }
    else
      format.html { render :new }
    end
  end
    
  end

  def edit
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    authorize @submission, :edit?
  end

  def update
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @submission.update_attributes(submission_params)
    authorize @submission, :update?
    redirect_to assignment_submissions_path(@assignment)
  end

  def destroy
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @submission.delete
    # authorize @submission, :destroy?
    redirect_to assignment_submissions_path(@assignment)
  end

  def review
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @submission.review!
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  def undone
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @submission.undone!
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  def done
    @assignment = Assignment.find params[:assignment_id]
    @submission = Submission.find(params[:id])
    @submission.done!
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  def create_comment
    @assignment = Assignment.find params[:assignment_id]
    @submission = @assignment.submissions.find params[:id]
    @comment = @submission.comments.create comment_params
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  def delete_comment
    @assignment = Assignment.find params[:assignment_id]
    @submission = @assignment.submissions.find params[:id]
    @comment = @submission.comments.find params[:comment_id]
    @comment.delete
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  private

  def submission_params
    params.require(:submission).permit(:name, :links)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.haml
.jumbotron  
  = form_for [@assignment, @submission] do |f|
    - if @submission.errors.any?
      #error_explanation
        %h2= "#{pluralize(@submission.errors.count, "error")} prohibited this submission from being saved:"
        %ul
          - @submission.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control", placeholder: "Fill out the name of the submitter"
    .form-group
      = f.label :links
      = f.text_field :links, class: "form-control", placeholder: "Provide links for your submissions"
    .form-group  
      = f.submit 'Save'

app/views/submissions/edit.html.haml
= render 'form'

app/views/submissions/index.html.haml
.jumbotron
  %center
    %h1.assignments Submissions
    - @assignment.submissions.each do |submission|
      %li
        %strong
          = link_to submission.name, assignment_submission_path(@assignment, submission)
          / = submission.link
          |
          = link_to "Edit", edit_assignment_submission_path(@assignment, submission)
          |
          = link_to "Delete", assignment_submission_path(@assignment, submission), method: :delete
  %br
  = button_to "Back to Assignment", assignments_path, class: "buttonlink", method: :get

app/views/submissions/new.html.haml
= render 'form'

app/views/submissions/show.html.haml
.jumbotron
  %center
    %h1
      = @submission.workflow_state
      %h2
      - if current_user.admin?
        .workflow_state
          - if @submission.workflow_state != "Complete"
            = link_to "Review", review_assignment_submission_path(@assignment, @submission), method: :put

          - if !['Done', 'Complete'].include?(@submission.workflow_state)
            = link_to "Undone", undone_assignment_submission_path(@assignment, @submission), method: :put

          - if !['Undone', 'Complete'].include?(@submission.workflow_state)
            = link_to "Done", done_assignment_submission_path(@assignment, @submission), method: :put

  %center
    %ul
    - @submission.comments.each do |comment|
      - if comment.content
        %li
          = comment.content
          = link_to "[Delete]", delete_comment_assignment_submission_path(@assignment, @submission, comment_id: comment.id), method: :delete

    = form_for @comment, url: create_comment_assignment_submission_path(@assignment, @submission) do |f|
      = f.label :content
      %br
      = f.text_area :content, :cols => "50", :rows => "10"
      %br
      = f.submit "Create Comment", class: "buttonlink"