config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'welcome#index'

resources :users

resources :locations do
  resources :cohorts do
    resources :students do
    end
  end
end

resources :assignments do
  resources :submissions do
    member do
    post :create_comment
    delete :delete_comment
    end
    member do
    put :review
    put :done
    put :undone
    end
  end
end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :cohorts
  has_many :users

  validates :city, presence: :true
  validates :description, presence: :true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @locations = Location.all
    authorize @locations, :index?
  end

  def show
    @location = Location.find params[:id]
    @cohorts = @location.cohorts
    authorize @location, :show?
  end

  def new
    @location = Location.new
    authorize @location, :create?
  end

  def create
    @location = Location.create location_params
    authorize @location, :create?
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully added!' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @location = Location.find params[:id]
    authorize @location, :edit?
  end

  def update
    @location = Location.find params[:id]
    authorize @location, :edit?
    @location.update_attributes location_params
    redirect_to locations_path
  end

  def destroy
    @location = Location.find params[:id]
    authorize @location, :destroy?
    @location.delete
    redirect_to locations_path
  end
  
  private
  def location_params
    params.require(:location).permit(:city, :description)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
.jumbotron  
  = form_for @location do |f|
    - if @location.errors.any?
      #error_explanation
        %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
        %ul
          - @location.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :city
      = f.text_field :city, class: "form-control", placeholder: "Which city would you like to add?"
    .form-group
      = f.label :description
      = f.text_field :description, :cols => "30", :rows => "10", class: "form-control", placeholder: "Give a brief description of your location"
      %br

      = f.submit 'Submit'

app/views/locations/edit.html.haml
%center
  %h1 Edit Location

  = render 'form'

app/views/locations/index.html.haml
%marquee
.jumbotron
  %center
    %h1.locations Locations
    = button_to "Add Location", new_location_path, method: :get, class: "buttonlink"
    %br
      - @locations.each do |location|
        %li
          %strong
            = link_to location.city, location_path(location)
            | 
            = location.description
            |
            = link_to "Edit", edit_location_path(location)
            |
            = link_to "Delete", location_path(location), method: :delete
    = button_to "Home", root_path, class: "buttonlink", method: :get

app/views/locations/new.html.haml
%center
  %h1 New Location

  = render 'form'

app/views/locations/show.html.haml
.jumbotron 
  %center
    %h1 Location
    %strong
      City
    = @location.city
    %br
    %strong
      Description
    = @location.description
    %br
    %br
    - if current_user.admin?
      = button_to "Add your cohort to our group!", new_location_cohort_path(@location), class: "buttonlink", method: :get
    %br
    %ul.cohort_list
      %h1
        Our Courses
        %h2
        - @location.cohorts.each do |cohort|
          %li
            %strong
              = link_to cohort.course, location_cohort_path(@location, cohort)
            |
            = link_to "Edit", edit_location_cohort_path(@location, cohort)
            |
            = link_to "Delete", location_cohort_path(@location, cohort), method: :delete